//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaboom
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backgroundMenu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int easyIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hardIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int iconList = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Screen = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Splash = 2130837511;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int MapButton = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int QuickButton = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int TutoButton = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int imageItem = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int linearText = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int listView = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int textBottom = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int textTop = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int widget28 = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LevelSelector = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ModeSelection = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
